version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: data-bunker-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: databunker
    ports:
      - "5432:5432"
    volumes:
      - data-bunker_postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  data-bunker_postgres-data:
    external: true
